### ISSUE TITLE
Preprocessing ds000221 (Notebook 2)

### ISSUE THREAD

**Issue by kaitj** [carpentries-incubator/SDC-BIDS-dMRI#11]
Perform preprocessing for new dataset `ds000221`. Previous preprocessing for `ds000030` made use of existing software and bash scripting prior to using `dipy` for processing. Would like to show some common preprocessing that is done (may exclude some steps that may be more specific to certain datasets / groups). Should also talk about existing software that helps with these steps. 

To do:
- [x] Brainmasking
- [x] Distortion correction (e.g. TOPUP)
- [x] Eddy correction
- [x] Registration with T1w 
- [x] Convert to carpentries format

Things to consider:
- [ ] Denoising
- [ ] Unringing
- [ ] Gradient nonlinearity (would not be done, but could point to resources)

Happy to hear some thoughts about what should be included or if anything is missing with the preprocessing.

**Comment by kaitj** [comment]
@josephmje @jhlegarreta Any thoughts on what else should/could be added to the preprocessing lesson? I'm hoping to start tackling some of items in this issue early next week. Previously with `ds000030`, only Eddy and registration with T1 was performed.

**Comment by josephmje** [comment]
Thanks for progressing on this @kaitj . I think we should stick with the steps you've listed in the To Do section. Those seem to be the minimal ones required. For the steps listed under Things to consider, I'm not sure if it would still be worth discussing them or leaving them out completely.

**Comment by jhlegarreta** [comment]
Looks good to me. A few additional steps that may be added:
- A `brain extraction` step could be added if not listed as a separate step/not done.
- Not sure if `resampling` the DWI to the T1w is understood as part of the `Registration with T1w` or if you usually consider it.
- Whether the DWI `normalization` is also something that should be considered.

**Comment by kaitj** [comment]
@jhlegarreta That is a good point and I can't recall at the moment if brain extracting was already included in the notebook, but have added it to the list. Resampling was also something that slipped my mind, but I can see it being a part of the "Registration with T1w". 

I'm not sure if we should include normalization as part of the notebook. Is there some consensus on this step? I have seen some groups do it (I also normally do it when I am pre-processing).

@josephmje I think of the things to consider, maybe denoising and unringing can be left out for now. I'm on the fence about the gradient nonlinearity correction. On one hand, I think it is important to at least be aware of, on the other hand, it would be more of a discussion point without being able to show the difference when performing this step using the `ds000221` dataset.

OVerall, I think we have some solid foundational steps here that I can start putting together in the lesson and if we decide to include the gradient stuff, that can always be added on afterwards.

**Comment by jhlegarreta** [comment]
>  That is a good point and I can't recall at the moment if brain extracting was already included in the notebook, but have added it to the list. 

:+1:

> Resampling was also something that slipped my mind, but I can see it being a part of the "Registration with T1w".

Yes, it can definitely be seen that way :+1:.

> I'm not sure if we should include normalization as part of the notebook. Is there some consensus on this step? I have seen some groups do it (I also normally do it when I am pre-processing).

We can maybe include/mention it as an optional step if we find that it is a controversial step.

Maybe the denoising and unringing can be at least mentioned as well, and be left for future development.

**Comment by kaitj** [comment]
Brainmasking, topup, and eddy is done. Running into some trouble with the registration step - currently running into some issues with getting a brainmask for the t1w.

Will try to get what has been processed uploaded to the OSF if I can find a way to efficiently upload multiple folders.

**Comment by kaitj** [comment]
> Brainmasking, topup, and eddy is done. Running into some trouble with the registration step - currently running into some issues with getting a brainmask for the t1w.

Got a rough, but decent mask for the anatomical after running bet twice on the second inversion of mp2rage. Will be working on the registration soon likely using the ANTs script that was previously used for ds000030 unless anyone has some alternative suggestions?

> Will try to get what has been processed uploaded to the OSF if I can find a way to efficiently upload multiple folders.

Files up to the eddy correction has been uploaded. Also included the anaotmical brainmask in the `uncorrected` folder

**Comment by jhlegarreta** [comment]
@kaitj looks like a good plan. As for the registration, I think ANTs should do a good job :ok_hand:.

**Comment by kaitj** [comment]
#21 addresses the first four points of this list.

**Comment by kaitj** [comment]
Believe at this point, this issue regarding notebook / lesson 2 should be done with latest PRs (#21 and #38)?

**Comment by jhlegarreta** [comment]
In the interest of moving forward, I'm fine closing the issue: the major items have been addressed (thanks @kaitj and @josephmje), and the data  we currently use may not strictly require the listed additional pre-processing steps (I have not strictly checked the quality).

So mentioning these in the lessons as possible additional steps depending on the data would be enough for now (and can be done even if we close this issue).

**Comment by kaitj** [comment]
Missed this comment before - closing issue with the above comment in mind.
