### ISSUE TITLE
Update figures

### ISSUE THREAD

**Issue by kaitj** [carpentries-incubator/SDC-BIDS-dMRI#131]
With slice orientations fixed (#121), figures will need to be updated accordingly. Episodes that make use of the utils call include
- [x] CSD
- [x] Deterministic tractography
- [x] Probabilistic tractography

**Comment by kaitj** [comment]
Am I missing any other notebooks that use the call @jhlegarreta ? Those were the ones that I could find.

**Comment by jhlegarreta** [comment]
> Am I missing any other notebooks that use the call @jhlegarreta ? Those were the ones that I could find.

Those are the ones.
