### ISSUE TITLE
Fix LaTeX equations

### ISSUE THREAD

**Issue by jhlegarreta** [carpentries-incubator/SDC-BIDS-dMRI#160]
LaTeX maths should be displayed appropriately: according to https://github.com/carpentries/carpentries-theme/commit/399bf2fd0086f94a29d7ad043b6ff9c8a40652ba they should be rendered appropriately. However, this lesson's LaTeX syntax are not being rendered as expected:
- `$r(s)$ ` in https://carpentries-incubator.github.io/SDC-BIDS-dMRI/local_tractography/index.html
- `$\theta$ in https://carpentries-incubator.github.io/SDC-BIDS-dMRI/probabilistic_tractography/index.html
- `$l$`, `$l_{max}$`, `$R = (l_{max}+1)(l_{max}+2)/2$`, `$R$, $l_{max} = {4, 6, 8}$`, and `$R = {15, 28, 45}$` in https://carpentries-incubator.github.io/SDC-BIDS-dMRI/constrained_spherical_deconvolution/index.html

Related issues and PRs
https://github.com/carpentries/styles/issues/296
https://github.com/carpentries/styles/pull/573
https://github.com/carpentries/styles/pull/592

**Comment by Alanocallaghan** [comment]
You need to set `math: true` in the md yaml frontmatter

**Comment by jhlegarreta** [comment]
@Alanocallaghan :100: Will give it a try. Much appreciated !!

**Comment by jhlegarreta** [comment]
@Alanocallaghan works like a charm. Thanks !
