### ISSUE TITLE
Combine solution and non-solution notebooks

### ISSUE THREAD

**Issue by josephmje** [carpentries-incubator/SDC-BIDS-dMRI#181]
I was playing around with the [Exercise2 extension](https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/exercise2/readme.html) for Jupyter. It seems really easy to set up and I think it would help us combine the solution and non-solution notebooks into a single file. 

Here's a demonstration below. The solution can be revealed by clicking on a button. You can also include a cell below the solution whether the learner is meant to enter their own code. Here, you could still include fill in the blank style content and have pytest skip those cells when running the tests.

![Peek 2021-08-12 16-52](https://user-images.githubusercontent.com/22102194/129268253-ad0c6dc3-059a-46eb-8d46-5f485b751624.gif)

WDYT? @kaitj @jhlegarreta

**Comment by jhlegarreta** [comment]
Would definitely save us work.

**Comment by jhlegarreta** [comment]
@josephmje Is it possible to have the solutuons enabled (e.g. using a flag) to test the relevant cells in the CI builds?
