### ISSUE TITLE
TypeError: 'int' object is not subscriptable

### ISSUE THREAD

**Issue by SnMtlb** [carpentries-incubator/SDC-BIDS-dMRI#210]
I get this error while running "response, ratio = auto_response_ssst(gtab, data, roi_radii=10, fa_thr=0.7)" for CSD section in Introduction to dMRI.
how can I fix it?

**Comment by jhlegarreta** [comment]
Please, do not cross post the same question in different repositories:
https://github.com/dipy/dipy/discussions/2607

Note that
- If you would like to increase your chances of getting an answer, please provide complete information about your platform, environment, etc.
- Our lesson gets tested on a regular basis on a Linux platform
https://github.com/carpentries-incubator/SDC-BIDS-dMRI/actions/workflows/build-test.yaml?query=branch%3Amain
(and DIPY gets tested even more thoroughly in their own repository). We may not be able to test the notebooks on other platforms.
- Our lesson requires some degree of knowledge in Python and MRI:
https://carpentries-incubator.github.io/SDC-BIDS-dMRI/index.html#prerequisites-for-learners
