### ISSUE TITLE
Test with Python 3.10, stop using Python 3.7

### ISSUE THREAD

**Issue by jhlegarreta** [carpentries-incubator/SDC-BIDS-dMRI#216]
Python 3.7 end-of-life is expected for 2023-06-27:
https://devguide.python.org/versions/#supported-versions

The GitHub actions should start using Python 3.10 (and even Python 3.11, expected to be released on 2022-10-24), and stop using Python 3.7, with the necessary Python package version upgrades.

**Comment by georgebisbas** [comment]
This looks like being resolved already here: https://github.com/carpentries-incubator/SDC-BIDS-dMRI/pull/217/files

**Comment by jhlegarreta** [comment]
Thanks for the heads-up @georgebisbas. Closing as completed in the mentioned PR.
