### ISSUE TITLE
vol_idx is a 1D-array containing the index of the first b0

### ISSUE THREAD

**Issue by AkhilaPhenomx** [carpentries-incubator/SDC-BIDS-dMRI#245]
Hi Team,
I am exploring Diffusion data and came across your repository and trying to replicate it with the sample data I have.
I didn't understanstand below step.

`# vol_idx is a 1D-array containing the index of the first b0`
`dwi_brain, dwi_mask = median_otsu(dwi_data, vol_idx=[0])`

what is the value of vol_idx in **Diffusion Preprocessing episode**?

**Comment by jhlegarreta** [comment]
`median_otsu` is a method that will compute the brain mask (remove the skull) and will return the mask and the brainmasked diffusion data. `vol_idx` tells which index of the input diffusion data (4D) volume is used to compute the mask. In this case, it is the first volume, corresponding to the index `[0]`, which holds the b0 image:
https://github.com/dipy/dipy/blob/4249da1987bad74cdc6cf1f69977b3a7132e7af8/dipy/segment/mask.py#L126
