### ISSUE TITLE
Improve how the CSD reconstruction lesson screenshots are displayed

### ISSUE THREAD

**Issue by jhlegarreta** [carpentries-incubator/SDC-BIDS-dMRI#29]
Improve how the CSD reconstruction lesson screenshots are displayed:
- [X] Make the screenshots be displayed inline instead of launching a separate `FURY` window
- [x] Add additional screenshots corresponding to the anatomical orientations.

**Comment by kaitj** [comment]
Just wanted to clarify what you meant by "corresponding to the anatomical orientations" so that I can add the screenshots you had in mind.

**Comment by jhlegarreta** [comment]
> Just wanted to clarify what you meant by "corresponding to the anatomical orientations" so that I can add the screenshots you had in mind.

All current views are axial: adding coronal and sagittal views would provide useful visual information (leaving aside the fact that the tractograms can contain non meaningful streamlines).

**Comment by kaitj** [comment]
Ahh that is fair. The current data is only a slice, so I'll turn it into a volume and show slices in each orientation. I also noticed it was using the original bvecs prior to eddy correction. Not sure if this was intended or if you had meant to use the eddy rotated bvecs. Either way, can be a quick change as i add in these screenshots.

**Comment by jhlegarreta** [comment]
> Ahh that is fair. The current data is only a slice, so I'll turn it into a volume and show slices in each orientation

Have not checked the script lately; using only a slice was maybe done on purpose to avoid long waiting times. If this is the case, maybe choosing slices in the other two orientations would be enough?

> I also noticed it was using the original bvecs prior to eddy correction. Not sure if this was intended or if you had meant to use the eddy rotated bvecs. Either way, can be a quick change as i add in these screenshots.

Not intended.

**Comment by kaitj** [comment]
Yep the slice was definitely intended to avoid long wait times, though a 30x30x30 volume seems to also run quick enough. And noted regarding the bvecs, Ive fixd and will push with the screenshot PR
