### ISSUE TITLE
BUG: `Github Actions` Test Failure

### ISSUE THREAD

**Issue by kaitj** [carpentries-incubator/SDC-BIDS-dMRI#31]
Good news is that the previously set up `Github Actions` now work. Bad news is it is failing when trying to install `pkg-resources==0.0.0` from the `requirements.txt`. 

Something to look into and fix to have valid tests!

**Comment by josephmje** [comment]
we might need to clean up the `requirements.txt` file. it looks like the result of a `pip freeze` but we could pare it down to only the packages that are used in the lessons. also, some packages install others so those wouldn't need to be included.

**Comment by jhlegarreta** [comment]
Thanks for the heads-up.

I did have the same issue when installing the packages locally and ended up by commenting that requirement.

On the one hand, I think having a fixed set of dependencies and versions ensures that the notebooks at least work with that set; on the other hand, if we get the CIs working and specify just the minimal set of packages that we explicitly import, that would be a guarantee that the notebooks work, and we would not need to rely on a `pip freeze`.

**Comment by jhlegarreta** [comment]
PR #39 will hopefully address this or at least provide the appropriate fixes for the tests to be run.

**Comment by jhlegarreta** [comment]
I think this can be closed: the builds are running the notebooks; the issues we face now (caching the data, the additional tools required, specifying the exact filename to the notebooks -i.e. solutions-, etc.) are being tracked in multiple threads.
