### ISSUE TITLE
Add a figure to the camera setup discussion

### ISSUE THREAD

**Issue by jhlegarreta** [carpentries-incubator/SDC-BIDS-dMRI#81]
Add a figure to the camera setup discussion. The contribution in PR #77 would benefit from a figure. Since creating it might take some time, it is left out of the PR so that the PR can be merged and the figure created and added as time permits.

Cross-referencing https://github.com/carpentries-incubator/SDC-BIDS-dMRI/pull/69#issuecomment-801897944 and https://github.com/carpentries-incubator/SDC-BIDS-dMRI/pull/77#issuecomment-804066412.

The figure can be added just after the pitch, roll and yaw are introduced with a text like:
```
The following figure illustrates these concepts and how they are related to the
anatomical orientations.

![3D scene camera viewpoint concepts and anatomical views]({{ base }}/fig/discuss/camera_viewpoint_concepts_anatomy.png){:class="img-responsive"}
```

**Comment by kaitj** [comment]
![Orientations](https://user-images.githubusercontent.com/21226986/112023931-13059980-8b0a-11eb-943c-a40fdb82a438.png)

Played around with a 3D model I had and can use this one. Open to suggestions though if we should change anything to this.

**Comment by jhlegarreta** [comment]
Looks good to me :+1: !
