### ISSUE TITLE
BUG: Github Actions Cache

### ISSUE THREAD

**Issue by kaitj** [carpentries-incubator/SDC-BIDS-dMRI#88]
First noticed in a different repository, but looking at the logs, it doesn't look like the cache is actually being used during the Github actions. Not a breaking issue, but probably something we want to look into.

**Comment by kaitj** [comment]
With #153 and the successful runs with caching, can this issue be closed?

@jhlegarreta @josephmje

**Comment by jhlegarreta** [comment]
Yes, the cache is working fine, so it can be closed. Thanks.
